env = "dev"

[server]
port = 2020
ip = "127.0.0.1"


[ipc]
port = 6868
password = "test_pwd"

[apm]
enabled = false
max_requests = 100
thread_limit = 10

[performance]
pool_enabled = false
pool_size = 10
pool_expire = 1000

[ui]
secret = "xnK82mcK7I9s_K3j-L8vK9L2m_N3o_P4q_R5s_T6u_V7w_X8y_Z9a_B0c_D1e"

[list]
test = ["eins", "zwei"]

[map]
test = {"key1"="value2", "key2"="value2"}
